const PDFDocument = require('pdfkit');
const { formatReference, getJournalFormatting, generateBibliography } = require('./citationFormatter');

function generatePDF(paper, references, style = 'APA') {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 72, bottom: 72, left: 72, right: 72 },
        info: {
          Title: paper.title || 'Academic Paper',
          Author: 'AI Academic Submission Engine',
          Subject: 'Academic Document'
        }
      });

      const chunks = [];
      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const formatting = getJournalFormatting(style);

      doc.fontSize(18)
        .font('Helvetica-Bold')
        .text(paper.title || 'Untitled Paper', { align: 'center' });

      doc.moveDown(0.5);
      doc.fontSize(10)
        .font('Helvetica')
        .fillColor('#666666')
        .text(`Formatted in ${style} style`, { align: 'center' });

      doc.fillColor('#000000');
      doc.moveDown(0.5);
      doc.moveTo(72, doc.y)
        .lineTo(doc.page.width - 72, doc.y)
        .stroke('#cccccc');
      doc.moveDown(1);

      if (paper.content) {
        const paragraphs = paper.content.split(/\n\s*\n/).filter(p => p.trim().length > 0);

        const sectionHeaders = [
          'abstract', 'introduction', 'background', 'literature review',
          'methodology', 'methods', 'results', 'discussion', 'conclusion',
          'acknowledgments', 'appendix'
        ];

        paragraphs.forEach(para => {
          const trimmed = para.trim();
          const lowerTrimmed = trimmed.toLowerCase().replace(/^\d+\.?\s*/, '');

          const isHeader = sectionHeaders.some(h =>
            lowerTrimmed === h || lowerTrimmed.startsWith(h + ':') || lowerTrimmed.startsWith(h + ' ')
          );

          if (doc.y > doc.page.height - 120) {
            doc.addPage();
          }

          if (isHeader) {
            doc.moveDown(0.8);
            doc.fontSize(14)
              .font('Helvetica-Bold')
              .text(trimmed.toUpperCase(), { align: 'left' });
            doc.moveDown(0.4);
          } else {
            doc.fontSize(11)
              .font('Helvetica')
              .text(trimmed, {
                align: 'justify',
                lineGap: formatting.spacing === 'double' ? 11 : 4,
                paragraphGap: 8
              });
            doc.moveDown(0.3);
          }
        });
      }

      if (references && references.length > 0) {
        doc.addPage();
        doc.fontSize(14)
          .font('Helvetica-Bold')
          .text(style === 'IEEE' ? 'REFERENCES' : 'References', { align: 'left' });

        doc.moveDown(0.5);
        doc.moveTo(72, doc.y)
          .lineTo(doc.page.width - 72, doc.y)
          .stroke('#cccccc');
        doc.moveDown(0.8);

        const parsedRefs = references.map(ref => {
          let authors = ref.authors;
          if (typeof authors === 'string') {
            try { authors = JSON.parse(authors); } catch { authors = [authors]; }
          }
          return { ...ref, authors };
        });

        parsedRefs.forEach((ref, idx) => {
          if (doc.y > doc.page.height - 100) {
            doc.addPage();
          }

          const formatted = formatReference(ref, style, idx + 1);

          doc.fontSize(10)
            .font('Helvetica')
            .text(formatted, {
              align: 'left',
              lineGap: 3,
              indent: style === 'APA' ? 36 : 0,
              paragraphGap: 0
            });

          if (ref.doi) {
            doc.fontSize(9)
              .fillColor('#1a73e8')
              .text(`https://doi.org/${ref.doi}`, {
                link: `https://doi.org/${ref.doi}`,
                underline: true,
                indent: style === 'APA' ? 36 : 0
              });
            doc.fillColor('#000000');
          }

          doc.moveDown(0.5);
        });
      }

      doc.moveDown(2);
      doc.fontSize(8)
        .fillColor('#999999')
        .text(
          `Generated by AI Academic Submission Engine | ${new Date().toLocaleDateString()} | References verified via Crossref & OpenAlex`,
          { align: 'center' }
        );

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { generatePDF };